### ISSUE TITLE
FlowCore package issue - I tried updating all, none or some (individually) Any idea?

### ISSUE THREAD

**Issue by fanaticfactoid** [SofieVG/FlowSOM#10]
package ‘flowCore’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘flowCore’

The downloaded binary packages are in
	C:\Users\priya\AppData\Local\Temp\Rtmp6bA2YF\downloaded_packages
installation path not writeable, unable to update packages: cluster, foreign, MASS, Matrix, nlme, survival
Old packages: 'bit', 'data.table', 'purrr', 'rlang', 'stringi'

Error output in R from FLowSOM plugin: 
suppressMessages(library("FlowSOM"))
Error: package or namespace load failed for 'FlowSOM' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'flowCore'
Execution halted

**Comment by SamGG** [comment]
Hi,
I got this error a couple of times. The problem comes fromm the fact that flowCore (or any other dependant package) is loaded in the current session or in another session. The packages must be unloaded before update. Typically, I close ALL RStudio application/project and ALL standard R session if any. Then I open RStudio and start a new project from scratch. That way, no package is loaded in the R session, because no object exists. Now, I always pdate any package successfully. Alternatively, I use a classical Rgui.
HTH

**Comment by fanaticfactoid** [comment]
Thanks, Sam. I tried as you suggested and closed all sessions and projects. Started a new Rstudio and new project. Still same error. I uninstalled Flowcore and re-installed with dependencies. It says package 'flowCore' not available for R 3.4.4. So, maybe I will download R 3.3 and see if it helps.

**Comment by SamGG** [comment]
Do not go to R3.3. Install flowcore, before installing flowsom.

**Comment by fanaticfactoid** [comment]
I tried that as well! It still asks me to update part of the package of flowCore.  
> biocLite("flowCore")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing package(s) ‘flowCore’
trying URL 'https://bioconductor.org/packages/3.6/bioc/bin/windows/contrib/3.4/flowCore_1.44.2.zip'
Content type 'application/zip' length 16712772 bytes (15.9 MB)
downloaded 15.9 MB

package ‘flowCore’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\priya\AppData\Local\Temp\RtmpaQY4GT\downloaded_packages
installation path not writeable, unable to update packages: cluster, foreign, MASS, Matrix, nlme, survival
Old packages: 'bit', 'data.table', 'purrr', 'rlang', 'stringi'
Update all/some/none? [a/s/n]:

**Comment by SamGG** [comment]
flowcore is now installed.
> package ‘flowCore’ successfully unpacked and MD5 sums checked
The remaining messages concern the "core" packages that were installed with R, and usually with the administrator rights. That's why as a standard user the path of those packages is not writeable.
> installation path not writeable ....
Try to install flowsom now.

**Comment by fanaticfactoid** [comment]
> library(FlowSOM)
Error: package or namespace load failed for ‘FlowSOM’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘robustbase’

**Comment by SamGG** [comment]
You entered the terrible loop of broken dependencies. Being patient, you can solve them one by one. Now install robustbase. You can use bioclite to it as well. Let me know.

**Comment by fanaticfactoid** [comment]
haha! Thanks. I will keep trying.

**Comment by fanaticfactoid** [comment]
It works now ! Thank you for your help.

**Comment by SamGG** [comment]
Good! I am not sure it really concerns flowsom.
Best, and don't forget to close this issue.
