### ISSUE TITLE
clarification of BuildSOM colsToUse

### ISSUE THREAD

**Issue by anaraserikbek** [SofieVG/FlowSOM#2]
Hi, I understand my question might be too simple, however, i have been trying to plot & experiment with different colsToUse parameters & still couldn't understand what it specifies.
when using the BuildSOM function of FlowSOM, the parameter colsToUse says it specifies column names or indices to use for building the SOM. However, in the tutorial the parameter is specified as colsToUse=c(9,12,14:18). Does this mean that the self-organizing map will be build using the columns 9 & 12, for markers 14 through 18?
ex: fSOM=BuildSOM(fSOM,colsToUse=c(9,12,14:18))

Thank you

**Comment by SofieVG** [comment]
Hi,

c(9,12,14:18) will just result in a vector, it is the same as c(9,12,14,15,16,17,18)
So the parameter colsToUse just takes 1 vector, in which I indicated here all the indices of the markers of interest. You could instead also give a vector of the column names, in this case this would correspond to c("Pacific Blue-A","APC-A","APC-Cy7-A","PE-A","PE-Texas Red-A","PE-Cy5-A","PE-Cy7-A")
In R, the columns of the matrix representing the flow data, corresponds to the markers, so this are not two separate things. Hopefully this clarifies how to use this function?

**Comment by anaraserikbek** [comment]
yes, thank you Sophie.
