### ISSUE TITLE
getIndiceMat not exported by new flowWorkspace version

### ISSUE THREAD

**Issue by DillonHammill** [SofieVG/FlowSOM#28]
Thanks for a great package!

Just a heads up, looks like `getIndiceMat` is no longer exported by the new version of `flowWorkspace` which is causing build errors. This is using the current GitHub version from the trunk branch 3.33.10.

```{r}
Error: object 'getIndiceMat' is not exported by 'namespace:flowWorkspace'
Execution halted
ERROR: lazy loading failed for package 'FlowSOM'
```

Cheers,
Dillon

**Comment by SofieVG** [comment]
Hi Dillon,

If you try the devel branch, it should work with the new version of
flowWorkspace. If it is released now, I will bring this update to the
master branch soon.

All the best,
Sofie

**Comment by DillonHammill** [comment]
Excellent! Thanks!

**Comment by Sithara85** [comment]
Hi, I am still experiencing issue with  'getIndiceMat' in flowWOrkspace. Is there any other function replaced this one?
