### ISSUE TITLE
PlotStars met: MST=2, plot grid option 

### ISSUE THREAD

**Issue by anaraserikbek** [SofieVG/FlowSOM#3]
When using PlotStars of FlowSOM and using MST=2, what does each grid of 10x10 represent? Why, even if the number of markers change, the grid size stays the same. Could you maybe give some reading on how exactly the tree is build & maybe some reading about the algorithm? 
Thank you

**Comment by SofieVG** [comment]
The nodes of the grid do not correspond to the markers: every node is a cluster of similar cells (so each node will have the amount of markers you defined, which can be shown in a star plot). You can vary the number of nodes in the grid by using the xdim and ydim parameters of the functions FlowSOM or BuildSOM. If the number of nodes (= xdim * ydim)  is too low, not all populations of interest will be splitted into separate nodes, but if the number is too high, the figures can become cluttered. In general, I work with a 7x7 grid (49 clusters), except when I know I'm looking for a rare population, when I use a 10x10 grid (100 clusters). Sometimes the occasion may ask for a different number of nodes, but this happens very rarely in my experience.
You can find our publication here: http://onlinelibrary.wiley.com/doi/10.1002/cyto.a.22625/abstract

**Comment by eghorani** [comment]
Dear Sofie,

Thanks for this excellent package!

I would like to PlotStars for an individual sample from the BuildMST object.

I've tried subsetting the BuildMST object using the FlowSOMSubset command:

fSOM2 <- FlowSOMSubset(fSOM,(fSOM$metaData[[1]][1]):(fSOM$metaData[[1]][2]))

And get the following error when attempting to pass fSOM2 to PlotStars...

Error in fsom$map$medianValues[, markers, drop = FALSE] : 
  no 'dimnames' attribute for array

For the unsubsetted BuildMST object, fsom$map$medianValues has markers for column names. The subsetted object has numbers instead. Maybe this is part of the issue....?

By adding back the correct column names to fsom$map$medianValues, the plot seems to work fine.

Perhaps I'm using your code incorrectly, or is this a bug that needs a small tweak in your code?

Thanks very much
