### ISSUE TITLE
Error while using CountGroups Function

### ISSUE THREAD

**Issue by pablasimarjot** [SofieVG/FlowSOM#30]
groupRes<-CountGroups(fSOM[[1]], fgroups)

Getting the following error while running the command above:

[1]"/path/Sample.fcs"
Error in newdata[, colnames(codes)] : subscript out of bounds

**Comment by tomerlan** [comment]
You probably applied FlowSOM to a subsetted FlowSet. If this is the case, you need to first re-write the subsetted FlowSet into fcs files and then read these new files rather than the originals with CountGroups.
