### ISSUE TITLE
Can FlowSOM be used for scRNA-seq data?

### ISSUE THREAD

**Issue by EDYAC** [SofieVG/FlowSOM#32]
Hello everyone,
I use FlowSOM in cytobank for CyTOF data, I was wondering if anyone have applied FlowSOM to scRNA-seq and compared it with other clustering methods?

Thank you!

**Comment by SamGG** [comment]
Hi,
I don't see any reason against. SOM is a clustering technique, was used in transcriptome analysis with micro-arrays... I think it is available as clustering in SeqGeq (FlowJo).
Best.

**Comment by SofieVG** [comment]
Hi,

One relevant adaptation is to include a PCA step upfront. In flow data typically the markers in the panel are chosen in such a way that they each contain relevant new information, while in RNA-seq you typically have many genes telling a very similar story, which would skew the clustering. With the Self-Organizing Map it is also important to make sure you first overcluster the data (potentially followed by a second metaclustering to come closer to the expected number of clusters, this is similar for flow data).

The Robinson lab did a benchmark study: https://f1000research.com/articles/7-1141/v3

All the best,
Sofie
