### ISSUE TITLE
Query - FlowSOM

### ISSUE THREAD

**Issue by santoshe1** [SofieVG/FlowSOM#36]
Hi Sofie,

Thank you for developing flowSOM. 

I had a question on how to find the number of cells within a particular cluster in a flowSOM object? 

Thank you,
Santosh

**Comment by SofieVG** [comment]
Dear Santosh,

The easiest way to get the number of cells in a cluster is probably
table(GetClusters(fsom)) with fsom your flowSOM object.

All the best,
Sofie

**Comment by santoshe1** [comment]
Thank you Sofie
