### ISSUE TITLE
Loading FlowSOM package fails

### ISSUE THREAD

**Issue by JPGranizo** [SofieVG/FlowSOM#37]
Hi,

when I try to load the FlowSOM package, then I receive an error message:

`> library(FlowSOM)`
`Error: package or namespace load failed for ‘FlowSOM’:
 object ‘compute_timestep’ is not exported by 'namespace:flowWorkspace'`

I am running macOS Catalina 10.15.7 and R version 4.0.3.
FlowSOM was installed via "BiocManager::install("FlowSOM")" and the installed FlowSOM version is 1.20.0
I tried to install FlowSOM via devtools::install_github("SofieVG/FlowSOM") or devtools::install_github("SofieVG/FlowSOM", ref = "devel") in case there is a more recent version. But the FlowSOM installation from github fails in both cases (see the error messages copied below).

I tried to load FlowSOM in combination with two different flowWorkspace versions: Version 4.0.6 installed via BiocManager and Version 4.1.12 installed from github. The flowWorkspace version does not have an effect on the error while loading FlowSOM.

Can you please advice how to fix loading FlowSOM?
Thank you very much in advance!

Error messages during the installation of FlowSOM from github:
> devtools::install_github("SofieVG/FlowSOM")
Downloading GitHub repo SofieVG/FlowSOM@HEAD
✓  checking for file ‘/private/var/folders/sl/6h6dh39d2p3617w8h3sf2bsm0000gn/T/RtmpR2sVJa/remotes10cf62afa7f5e/SofieVG-FlowSOM-6f79b8b/DESCRIPTION’ ...
─  preparing ‘FlowSOM’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘FlowSOM_1.19.4.tar.gz’
   
* installing *source* package ‘FlowSOM’ ...
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c som.c -o som.o
som.c:37:18: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
        xdist += abs(tmp);
                 ^
som.c:37:18: note: use function 'fabs' instead
        xdist += abs(tmp);
                 ^~~
                 fabs
som.c:47:15: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
        tmp = abs(tmp);
              ^
som.c:47:15: note: use function 'fabs' instead
        tmp = abs(tmp);
              ^~~
              fabs
som.c:134:27: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
                change += abs(tmp);
                          ^
som.c:134:27: note: use function 'fabs' instead
                change += abs(tmp);
                          ^~~
                          fabs
3 warnings generated.
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o FlowSOM.so som.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-FlowSOM/00new/FlowSOM/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/flowWorkspace/libs/flowWorkspace.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/flowWorkspace/libs/flowWorkspace.so, 6): Symbol not found: __ZN7cytolib11H5CytoFrameC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS_14FCS_READ_PARAMES9_b
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/flowWorkspace/libs/flowWorkspace.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/flowWorkspace/libs/flowWorkspace.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘FlowSOM’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/FlowSOM’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/FlowSOM’
Error: Failed to install 'FlowSOM' from GitHub:
  (converted from warning) installation of package ‘/var/folders/sl/6h6dh39d2p3617w8h3sf2bsm0000gn/T//RtmpR2sVJa/file10cf623c00a5d/FlowSOM_1.19.4.tar.gz’ had non-zero exit status

**Comment by yuhuisunnyluo** [comment]
Hi, I use flowSOM via Rstudio, and don't have this problem

**Comment by JPGranizo** [comment]
_Hi, I use flowSOM via Rstudio, and don't have this problem_

Hi, which R version and which FlowSOM / flowWorkspace versions have you installed?

**Comment by SofieVG** [comment]
Hi,

I haven't encountered this issue and do not think we call this
compute_timestep function anywhere in the FlowSOM code. The
compute_timestep function seems to be from an older version of
flowWorkspace though. Maybe try to update all packages, that another
dependency of FlowSOM used this older function and gets loaded  when trying
to load FlowSOM?

All the best,
Sofie

**Comment by SofieVG** [comment]
Hi @JPGranizo,

As I could not replicate this error and a newer version of the FlowSOM package has been pushed to github in the meantime, I will close this issue for now. If updating the packages didn't work and you're still encountering issues with the newest FlowSOM version, feel free to reopen this issue or start a new one.
