### ISSUE TITLE
GetFlowJoLabels error: FCS files not found

### ISSUE THREAD

**Issue by vetgreg** [SofieVG/FlowSOM#44]
Hi!
I am working with some flow cytometry data. We initially employed a cleaning strategy in Flow Jo by using FlowAI. We exported the good events into new FCS files, made the gating strategy in a FlowJo workspace and applied a R script to build the FlowSOM analysis, which worked quite well. However, we decided to re-build the analysis using only the CD4+ population. We exported the CD4+ population (from the "good events" exported FCS files) into new FCS files, but when we try to use the GetFlowJoLabels command it returns with the following error:

> manual <- GetFlowJoLabels(list_fcs, gating_wsp, cell_types = cell_types)
[1] "Processing export_t panel 02_A2_Viable_CD4+.fcs"
Error in GetFlowJoLabels(list_fcs, gating_wsp, cell_types = cell_types) :
  File not found. Files available:
export_t panel 02_A2_Viable_CD4+.fcs
export_t panel 03_A2_Viable_CD4+.fcs
export_t panel 04_A2_Viable_CD4+.fcs
...

As you see, it reports that the file is not found, but the files available has exactly the same name. We double checked that names in the "list_fcs", "gating_wsp" and the fcs files has the same name.

**Comment by SofieVG** [comment]
Hi,

I think this might be an issue with the + sign in the file names. Are you sure you are working on the latest FlowSOM version? We recently tried to make this more robust, but if the problem persist in the current version I will have another look at it... 

All the best,
Sofie

**Comment by vetgreg** [comment]
Hi Sofie, 

Many thanks to the answer. We tried to exclude the + sign, but the problem persisted. After all, I create a new workspace and start over again. Meanwhile I updated the FlowSOM version. Now everything is working, but I really have no guess where the problem came from.

best regards!
Greg
