### ISSUE TITLE
Release version out of date compared to Flowjo Plugin.

### ISSUE THREAD

**Issue by AlexanderWMacFarlaneIV** [SofieVG/FlowSOM#53]
Hello.

I am interested in running FlowSOM with custom code in R.
I currently use the plugin version for Flowjo.

The Flowjo version is up to 3.0.18, and was released recently.
The version available here is more than 5 years old.

Can I get a copy of the most recent release?

**Comment by yuhuisunnyluo** [comment]
I believe that you will need to pay for a Flowjo license that keeps the software up to date.

**Comment by SofieVG** [comment]
If you install the version from github with the following command, you will
have the most recent version:
devtools::install_github("saeyslab/FlowSOM", build_vignettes = TRUE)
