### ISSUE TITLE
Building error on Bioconductor

### ISSUE THREAD

**Issue by Kayla-Morrell** [SofieVG/FlowSOM#56]
Hello Sofie,
 
I tried to send the following email to you via the email listed in the DESCRIPTION file
but it was undeliverable. Please double check that this email is correct so that we may
be able to contact you in the future. It is crucial that the packages within Bioconductor
list an active maintainer email that responds to inquires.

The next Bioconductor release 3.16 is scheduled for November 2nd. Commits to the
current 3.15 release should be made by October 14th and the last day to commit
to the devel branch is October 28th. We like to make an effort to have all
Bioconductor packages building and checking without ERROR or TIMEOUT in both
release and devel versions.
 
Currently your package is producing an ERROR on the Windows builder in both
the release and devel versions of Bioconductor. Could you please investigate
the error as soon as possible?
 
Release version - https://bioconductor.org/checkResults/3.15/bioc-LATEST/FlowSOM/
Devel version - https://bioconductor.org/checkResults/3.16/bioc-LATEST/FlowSOM/
 
If you need any assistance please feel free to ask questions at
[bioc-devel@r-project.org](mailto:bioc-devel@r-project.org).
 
Thank you,
Kayla

**Comment by SamGG** [comment]
@Kayla-Morrell That might be the reason why I could not install FlowSOM under Windows in binary mode this afternoon. I don't understand why the same C code is passing checks under Linux but not Windows. This sounds like it is due to external libraries. While being not part of the dev team, I will have a look.
@SofieVG I sincerely believe that FlowSOM should stay in BC. Hope to bring some clue.

**Comment by SamGG** [comment]
Hi,

Current version from this repo is OK on my fresh install of R421, Bioc 3.15 under Windows10. It is also OK in the 3.16 devel branch of Bioc. There is only a note concerning the C code compilation in the check process, but this note is not present in the install process. Not the same compilation options?

XML package is not used in FlowSOM, so could be safely removed from `DESCRIPTION`; it will be installed as a requirement of flowWorkspace which is part of `Suggests:`. In fact the following could be safely removed and the documentation rebuilt to update `NAMESPACE`.
https://github.com/SofieVG/FlowSOM/blob/c70beb09ca2242e0d6e75956d460a5120a749898/R/0_FlowSOM.R#L88
In the vignette there should an 's' after color
https://github.com/SofieVG/FlowSOM/blob/c70beb09ca2242e0d6e75956d460a5120a749898/vignettes/FlowSOM.Rnw#L337
Not sure I will test the current version of Bioc 3.15. Let me know.

Best.
