### ISSUE TITLE
Porting FlowSOM to python

### ISSUE THREAD

**Issue by ngreenwald** [SofieVG/FlowSOM#58]
Hi @SofieVG, 
We are thinking about porting FlowSOM to python so that it can integrate more seamlessly into our pipeline. We would make the resulting repo open source, but we just wanted to check in with you before starting to make sure that's okay. There's currently not a license on the repo.

Thanks,
Noah

**Comment by SofieVG** [comment]
Dear Noah,

Apologies for my slow reply. FlowSOM is under the GPL (>= 2) license (it is mentioned in the DESCRIPTION file). 
So certainly okay to port FlowSOM to python, I'm happy for everyone to be able to use it as smoothly as possible!

All the best,
Sofie
