### ISSUE TITLE
Using `importance` argument for SOM mapping?

### ISSUE THREAD

**Issue by mdmanurung** [SofieVG/FlowSOM#61]
Hello,

I saw that FlowSOM has an argument to weight markers with the `importance` argument, in which the expression values were multiplied by whatever factor that the user put in. However, as far as I know, this argument is not used frequently. I naively thought that it makes sense to weight a marker differently so that it drive the clustering, especially when considering prior knowledge. Do you have any thoughts that you can share about this or should I just stay away?

Cheers,
Mikhael

**Comment by SofieVG** [comment]
Dear Mikhael,

While it might indeed be helpful in specific cases, in my experience it is often quite difficult to put exact numerical weight values based on more abstract prior knowledge. Therefore, I don't use it often, but if it would be helpful in your case certainly feel free to explore it!

Kind regards,
Sofie

**Comment by mdmanurung** [comment]
Thank you for sharing your thoughts!
