### ISSUE TITLE
SOM function: check codes vs grid and data

### ISSUE THREAD

**Issue by SamGG** [SofieVG/FlowSOM#7]
Hi,
May I suggest that, if codes is not null, the SOM function should verify:
- ncol(codes) == ncol(data)
- nrow(codes) == xdim * ydim

https://github.com/SofieVG/FlowSOM/blob/af08bb6f6a61f8c594300fa45d5d9f3d0da0e9f8/R/2_buildSOM.R#L95-L98

Cheers.

**Comment by SofieVG** [comment]
Thank you for the suggestion, this has been added to the code.
