### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by omega1119** [SofieVG/FlowSOM#8]
Hi there,

when we apply flowSOM in FlowJo to one of our populations the flowSOM csv output file is missing. Instead the only file we can find in the flowSOM folder is the following: 
SYN 101_Tube_004_015.LiveCD3+.ExtNode.csv

Please see the below FlowJo engine log:

`<FCML engineId="ExE974859553" >
  <FcmlQuery msg="File does not exist: D:\xxxxx\FlowSOM\SYN_101_Tube_004_015.LiveCD3+.csv.flowSOM.csv" >
    <FlowSOM version="1.0"  showOutput="1"  timeInMs="32" >
      <Option view="MST" />
      <Option pdf="1" />
      <Option fixedNodeSize="1" />
      <Option MFIsInTable="0" />
      <Option plot="All as piecharts" />
      <Option applyOn="None" />
      <Option ydim="10" />
      <Option xdim="10" />
      <Option scale="1" />
      <Option nodeScale="100.0" />
      <Option nClus="8" />
      <Option bgMetaClusters="1" />
      <Parameter name="Comp-FITC-A" />
      <Parameter name="Comp-PE-A" />
      <Parameter name="Comp-PerCP-Cy5-5-A" />
      <Parameter name="Comp-APC-A" />
      <Parameter name="Comp-BV 421-A" />
    </FlowSOM>
    <Export/>
    <Error/>
  </FcmlQuery>
</FCML>`

**Comment by SofieVG** [comment]
Hi, 
This probably means that the R script failed at some point, and therefor the final csv was not created. If you check the checkbox "Save the Rscript and output messages", do you see a file "Rscript.FlowSOM.[some_numbers].txt" created next to this first csv file? 
If so, could you share this with me to help debug the problem? 
If not, FlowJo still has an issue with connecting with R. In this case, it is not a FlowSOM specific problem and I would recommend you to contact the FlowJo helpdesk, as they will be able to help you better. Keep in mind that this also fails on mac when there are any spaces in your path to the workspace (FlowJo is aware of this and will hopefully fix this in the future).

**Comment by omega1119** [comment]
Hi,

turns out the issue was the R path in the FlowJo preferences. I had not selected the correct path to the bin folder. That's been corrected now and the plugin works on Windows. Thanks!
